apiVersion: apps/v1
kind: Deployment
metadata:
  name: oms-tracking
  namespace: order-domain
  labels:
    app: oms-tracking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oms-tracking
  template:
    metadata:
      labels:
        app: oms-tracking
    spec:
      containers:
      - name: oms-tracking
        image: manishsrivastavaggn/oms-tracking:changeMePlease
        ports:
        - containerPort: 8080
        