apiVersion: v1
kind: Service
metadata:
  name: oms-tracking-svc
  namespace: order-domain
  labels:
    app: oms-product
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: oms-tracking
  

